In [1]:
import numpy as np

# Lists
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
print(type(list1))  # <class 'list'>

# Arrays
array1 = np.array(list1)
array2 = np.array(list2)
print(type(array1))  # <class 'numpy.ndarray'>

# Mathematical Operations
multiplication = array1 * array2
division = array2 / array1
power = array1 ** 2

print("Multiplication:\n", multiplication)
print("Division:\n", division)
print("Power:\n", power)

# Combine Text with NumPy function
textual_output = f"Addition of Two: array1 + array2 = {array1 + array2}"
print(textual_output)

# NumPy functions
sin_values = np.sin(array1)
log_values = np.log(array1)
log2_values = np.log2(array1)
exp_values = np.exp(array1)

print("Sine values:\n", sin_values)
print("Natural Log values:\n", log_values)
print("Log base 2 values:\n", log2_values)
print("Exponential values:\n", exp_values)

<class 'list'>
<class 'numpy.ndarray'>
Multiplication:
 [ 6 14 24 36 50]
Division:
 [6.         3.5        2.66666667 2.25       2.        ]
Power:
 [ 1  4  9 16 25]
Addition of Two: array1 + array2 = [ 7  9 11 13 15]
Sine values:
 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural Log values:
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Log base 2 values:
 [0.         1.         1.5849625  2.         2.32192809]
Exponential values:
 [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
